version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../app/backend/database:/app/backend/database
    environment:
      - NODE_ENV=production
    restart: unless-stopped 