name: Docker Build and Save

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-save:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: battlepair:latest
          file: ./docker/Dockerfile

      - name: Save Docker image as tar
        run: |
          docker save battlepair:latest -o battlepair.tar
          gzip battlepair.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: battlepair-docker-image
          path: battlepair.tar.gz
          retention-days: 5 